trailing_comma = "Never"
fn_params_layout = "Compressed"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
unstable_features = true
max_width = 150
style_edition = "2021"
chain_width=60